### ISSUE TITLE
issue with install

### ISSUE THREAD

**Issue by vsoch** [lsst-sqre/zenodio#2]
it looks like there is an issue in the setup.py with getting the description from the README

```
  Collecting git+git://github.com/lsst-sqre/zenodio.git
    Cloning git://github.com/lsst-sqre/zenodio.git to /tmp/pip-g3E4L6-build
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-g3E4L6-build/setup.py", line 20, in <module>
            long_description = read('README.rst')
          File "/tmp/pip-g3E4L6-build/setup.py", line 18, in read
            return open(full_filename, mode='r', encoding='utf8').read()
        TypeError: 'encoding' is an invalid keyword argument for this function
```

is anyone using this module?

**Comment by vsoch** [comment]
ah, does this only work with python 3+? I didn't see that in the docs.

**Comment by vsoch** [comment]
yep works for that! Sorry about that! :)
